### ISSUE TITLE
Investigate and write unit tests for DID-JWT to unearth issue with returning MNIDS for legacy code

### ISSUE THREAD

**Issue by Eseoghene** [uport-project/iis#160]
Ti&m has an issue where legacy user IDs JWT return in the address key value did:uport:Mnid and currently want all legacy IDs to return the value without the did prefix.

Debug and proffer best solution to this which would result in updating the did-jwt dependency in the app and libraries

**Comment by mi-xu** [comment]
After discussing with @aldigjo and @zachferland, we decided that a code change in the libraries is not necessary to solving the problem that Ti&M is experiencing (they want the issuer of a selective disclosure response to be an mnid instead of a did if the client id making the request is an mnid).

The undesired (but not incorrect by design) behavior is occurring in the `Credentials` [constructor](https://github.com/uport-project/uport-js/blob/00ecf8c696ae68e3a04353913a9edfb3b6e710b2/src/Credentials.js#L96), where the object's `did` attribute is being set by prepending "did:uport:" to the mnid passed through the `settings.address` param.  One way to avoid this is by instantiating the `Credentials` object using `settings.did` to pass the mnid instead.

@aldigjo will be changing the mobile app code to create `Credentials` this way when responding to a selective disclosure request. https://app.zenhub.com/workspace/o/uport-project/iis/issues/161

Additionally, we will include the change to export `normalizeDID` that @rmw2 made in https://github.com/uport-project/did-jwt/pull/19 to make it easier for devs to handle similar situations moving forward.
